(function(){
'use strict';
const ARABIC=/[\u0600-\u06FF]/;
let lang=localStorage.getItem('lc-language')==='en'?'en':'ar';
const originalText=new WeakMap(), originalAttrs=new WeakMap();
const T=new Map([
['محلل الروابط السيبراني','Cyber Link Analyzer'],['تغيير المظهر','Change theme'],
['تحقق من أمان','Check the safety of'],['الرابط قبل فتحه','a link before opening it'],
['نظام متعدد المؤشرات لتحليل بنية URL واكتشاف مؤشرات التصيد وانتحال النطاقات وروابط QR دون فتح الرابط المستهدف.','A multi-indicator system that analyzes URL structure and detects phishing signals, domain impersonation, and suspicious QR links without opening the target link.'],
['أقسام الموقع','Site sections'],['🔗 تحليل الرابط','🔗 Link Analysis'],['📷 تحليل QR','📷 QR Analysis'],['📊 اختبار النظام','📊 System Test'],['ℹ️ كيف يعمل','ℹ️ How It Works'],['🔐 الخصوصية','🔐 Privacy'],
['أدخل الرابط','Enter a link'],['الرابط المراد تحليله','Link to analyze'],['🔍 فحص الرابط','🔍 Analyze Link'],
['التحليل المحلي لا يفتح الرابط ولا يحمل محتواه. التحقق الخارجي عبر VirusTotal اختياري ويحتاج إلى ضغط الزر.','Local analysis does not open the link or load its content. External VirusTotal verification is optional and runs only when you request it.'],
['مميزات النظام','System features'],['تحليل محلي سريع','Fast local analysis'],['يحلل بنية الرابط قبل فتحه ويعرض Evidence قابلة للتفسير.','Analyzes the URL structure before opening it and displays explainable evidence.'],['انتحال النطاقات','Domain impersonation'],['Levenshtein ومؤشرات الاستبدال البصري مع استثناء النطاقات الرسمية.','Uses Levenshtein similarity and visual-substitution indicators while excluding official domains.'],['سمعة خارجية اختيارية','Optional external reputation check'],['يمكن للمستخدم طلب فحص VirusTotal من خلال Backend آمن.','The user can request a VirusTotal check through a secure backend.'],
['فحص رمز QR','QR Code Scanner'],['استخدم الكاميرا أو ارفع صورة QR. إذا كان المحتوى رابطًا، سيتم استخراج الرابط وتحليله دون فتحه.','Use the camera or upload a QR image. If it contains a link, the URL will be extracted and analyzed without opening it.'],['📷 تشغيل الكاميرا','📷 Start Camera'],['⏹ إيقاف الكاميرا','⏹ Stop Camera'],['🖼️ رفع صورة QR','🖼️ Upload QR Image'],['⚠️ تم استخراج الرابط من QR ولم يتم فتحه تلقائيًا.','⚠️ The link was extracted from the QR code and was not opened automatically.'],
['مجموعة Prototype Benchmark اصطناعية قابلة للتوسعة. النتائج لا تمثل أداء النظام على الإنترنت بالكامل.','An extensible synthetic prototype benchmark. Results do not represent the system’s full performance on the internet.'],['▶ تشغيل الاختبارات','▶ Run Tests'],['لم يتم تشغيل الاختبارات بعد.','Tests have not been run yet.'],
['ℹ️ كيف يعمل النظام؟','ℹ️ How Does the System Work?'],
['إدخال الرابط:','Link input:'],['يتحقق LC من صيغة HTTP/HTTPS قبل التحليل.','LC validates the HTTP/HTTPS format before analysis.'],['يفصل البروتوكول وhostname والمنافذ والمسار والمعاملات.','Separates the protocol, hostname, ports, path, and parameters.'],['تحليل URL:','URL analysis:'],['يفحص IP وuserinfo و@ وPunycode وUnicode وطول الرابط والنطاقات الفرعية والمنافذ والترميز والكلمات والمعاملات والروابط المختصرة.','Checks IP usage, userinfo, @, Punycode, Unicode, URL length, subdomains, ports, encoding, keywords, parameters, and URL shorteners.'],['يقارن النطاق المسجل بعلامات معروفة باستخدام Levenshtein والاستبدالات البصرية، مع استثناء النطاق الرسمي.','Compares the registered domain with known brands using Levenshtein distance and visual substitutions, while excluding official domains.'],['يجمع Evidence بأوزان واضحة ويخرج Risk Score من 0 إلى 100.','Combines weighted evidence and produces a risk score from 0 to 100.'],['يستخرج محتوى QR من الكاميرا أو الصورة، ثم يمرر الرابط إلى نفس مسار التحليل دون فتحه.','Extracts QR content from the camera or an image, then sends the URL through the same analysis flow without opening it.'],['لا يتم إرسال الرابط للخدمة الخارجية إلا عندما يختار المستخدم ذلك.','The link is sent to the external service only when the user chooses to do so.'],['النتيجة:','Result:'],['تعرض الدرجة والمؤشرات وأسبابها والتوصية، دون الادعاء أن الرابط آمن 100%.','Displays the score, indicators, reasons, and recommendation without claiming that a link is 100% safe.'],['الصياغة الأساسية:','Core wording:'],['«لم يتم اكتشاف مؤشرات خطورة واضحة ضمن الفحوصات المتاحة.» تعني أن الفحوصات الحالية لم تجد مؤشرات واضحة، وليست ضمانًا لأمان الرابط.','“No clear risk indicators were detected by the available checks” means the current checks found no clear indicators; it is not a guarantee that the link is safe.'],
['🔐 الخصوصية','🔐 Privacy'],['التحليل المحلي:','Local analysis:'],['يتم داخل المتصفح اعتمادًا على خصائص URL، ولا يحتاج إلى فتح الصفحة المستهدفة.','Runs inside the browser using URL properties and does not need to open the target page.'],['خدمة خارجية اختيارية. عند الضغط على «تحقق خارجي عبر VirusTotal» يتم إرسال الرابط إلى Backend المشروع ثم إلى VirusTotal للتحقق من السمعة.','An optional external service. When “External check via VirusTotal” is selected, the URL is sent to the project backend and then to VirusTotal for a reputation check.'],['عدم فتح الروابط:','No automatic link opening:'],['LC لا يفتح الرابط الذي يتم تحليله تلقائيًا، بما في ذلك الروابط المستخرجة من QR.','LC never automatically opens the analyzed link, including links extracted from QR codes.'],['بيانات الاعتماد:','Credentials:'],['LC لا يطلب أو يجمع كلمات مرور المستخدمين. إذا احتوى الرابط على userinfo، يعرض LC وجودها دون عرض كلمة المرور في Evidence، ولا يرسل هذا الرابط للتحقق الخارجي.','LC does not request or collect user passwords. If a URL contains userinfo, LC reports its presence without exposing the password in the evidence and does not send that URL for external verification.'],['المفتاح السري:','Secret key:'],['مفتاح VirusTotal لا يوجد في JavaScript الخاص بواجهة GitHub Pages؛ يجب حفظه في متغير بيئة داخل Backend.','The VirusTotal key is not stored in the GitHub Pages JavaScript; it must be kept in a backend environment variable.'],
['أداة تعليمية لتحليل مؤشرات URL. لا تضمن أن الرابط آمن أو خبيث.','An educational tool for analyzing URL indicators. It does not guarantee that a link is safe or malicious.'],
['منخفض','Low'],['متوسط','Medium'],['مرتفع','High'],['حرج','Critical'],['مؤشر الخطورة المحلي','Local risk score'],['لا توجد مؤشرات مكتشفة في الفحوصات المحلية الحالية.','No indicators were detected by the current local checks.'],['🛡️ تحقق خارجي عبر VirusTotal','🛡️ External Check via VirusTotal'],['لن يتم إرسال الرابط إلى VirusTotal إلا عند اختيار التحقق الخارجي.','The URL will be sent to VirusTotal only when you choose external verification.'],['⚠️ أدخل رابطًا أولًا','⚠️ Enter a link first'],['ضع الرابط في الخانة ثم اضغط فحص الرابط.','Enter the link in the field, then press Analyze Link.'],['❌ الرابط غير صالح','❌ Invalid link'],['تعذر تحليل الرابط.','The link could not be analyzed.'],['نجح','Passed'],['فشل','Failed']
]);
function tr(s){
 if(!s||!ARABIC.test(s)) return s;
 let out=s;
 [...T.entries()].sort((a,b)=>b[0].length-a[0].length).forEach(([a,b])=>{out=out.split(a).join(b)});
 out=out.replace(/تم تشغيل (\d+) حالة: (\d+) ناجحة و(\d+) فاشلة\./g,'Ran $1 cases: $2 passed and $3 failed.');
 out=out.replace(/الرابط الذي تم تحليله:/g,'Analyzed link:').replace(/المؤشرات المكتشفة \((\d+)\)/g,'Detected indicators ($1)');
 if(ARABIC.test(out)) out=out.replace(/[\u0600-\u06FF][\u0600-\u06FF\s،؛؟«»ًٌٍَُِّْـ]*/g,'').replace(/\s{2,}/g,' ').trim() || 'English information';
 return out;
}
function walk(root){
 if(root.nodeType===Node.TEXT_NODE){if(!originalText.has(root)) originalText.set(root,root.nodeValue);root.nodeValue=lang==='en'?tr(originalText.get(root)):originalText.get(root);return;}
 if(root.nodeType!==Node.ELEMENT_NODE) return;
 ['aria-label','title','placeholder'].forEach(a=>{if(root.hasAttribute(a)){let m=originalAttrs.get(root)||{};if(!(a in m))m[a]=root.getAttribute(a);originalAttrs.set(root,m);root.setAttribute(a,lang==='en'?tr(m[a]):m[a]);}});
 root.childNodes.forEach(walk);
}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';walk(document.body);const b=document.getElementById('langBtn');if(b)b.textContent=lang==='en'?'AR':'EN';document.title=lang==='en'?'Cyber Link Analyzer | URL Security Analyzer':'Cyber Link Analyzer | محلل الروابط السيبراني';}
document.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('langBtn');if(b)b.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('lc-language',lang);apply();});apply();new MutationObserver(ms=>{if(lang!=='en')return;ms.forEach(m=>m.addedNodes.forEach(n=>walk(n)));}).observe(document.body,{childList:true,subtree:true});});
window.CyberLinkLanguage={get language(){return lang},apply};
})();
